{
  imports = [
    ./hyprland.nix
    ./hyprlauncher.nix
    ./hyprpaper.nix
    ./hyprtoolkit.nix
    ./waybar.nix
    ./fonts.nix
    ./kitty.nix
    ./shell.nix
    ./neovim
    ./swaync.nix
    ./locale.nix
    ./palette.nix
    ./greetd.nix
    ./applications.nix
    ./hyprlock.nix
    ./cliphist.nix
    ./librewolf.nix
    ./docker.nix
    ./git.nix
    ./bluetooth.nix
    ./secrets.nix
    ./nix.nix
    ./java.nix
  ];
}
